blueprints/mail.py
from flask import *
from sqlalchemy.orm import relationship

from blueprints.forms import *
from decorators import *
from model import *

bp = Blueprint('mail', __name__, url_prefix='/mail')


@bp.route('/mail_main', methods=['GET', 'POST'])
@login_required
def mail_main():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    # print(g.name, g.id)
    # print(session['admin_id'])  # 不知道为什么 g.id就没法用，会提示没有这个属性，只好从session里面取
    my_emails = [email for email in emails if session['admin_id'] == email.receiver_id and
                 email.is_trash == 0 and email.is_draft == 0]

    return render_template('d_mail.html', emails=my_emails)


@bp.route('/mail_view/<mail_id>', methods=['GET', 'POST'])
@login_required
def mail_view(mail_id):
    email = EmailModel.query.filter_by(id=mail_id)
    email[0].is_read = True
    print(email[0].id, email[0].is_read)
    admin_id = session['admin_id']
    emails = EmailModel.query.filter_by(sender_id=admin_id)
    cnt = 0
    for e in emails:
        cnt += 1
    db.session.commit()
    return render_template('d_mail_view.html', email=email[0], length=cnt)


@bp.route('/throw2trash/<mail_id>')
@login_required
def throw2trash(mail_id):
    email = EmailModel.query.filter_by(id=mail_id).first()
    if email.is_trash == 1:
        email.is_trash = 0
    else:
        email.is_trash = 1
    print('邮件状态已修改', email.is_trash)
    db.session.commit()
    return redirect(url_for('mail.trash'))


@bp.route('/delete_in_trash/<mail_id>')
@login_required
def delete_in_trash(mail_id):
    email = EmailModel.query.filter_by(id=mail_id).first()
    db.session.delete(email)
    db.session.commit()
    return redirect(url_for('mail.trash'))


@bp.route('/compose', methods=['GET', 'POST'])
@login_required
def compose():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    my_emails = [email for email in emails if session['admin_id'] == email.receiver_id]
    recent_id = []
    recent_name = []
    for me in my_emails:
        recent_id.append(me.sender_id)
    admins = AdminModel.query.order_by(AdminModel.id).all()
    for a in admins:
        if a.id in recent_id:
            recent_name.append(a.name)

    if request.method == 'GET':
        return render_template('d_mail_compose.html', recent_name=recent_name)
    else:
        form = ComposeForm(request.form)
        if form.validate():
            receiver_name = form.receiver_name.data[0:-13]
            receiver_id = AdminModel.query.filter_by(name=receiver_name).first().id
            title = form.title.data
            content = form.content.data
            # admin = AdminModel.query.filter_by(id=receiver_id).first()
            if not receiver_id:
                return render_template('d_mail_compose.html', error_msg='无此用户', recent_name=recent_name)
            elif receiver_id == session['admin_id']:
                return render_template('d_mail_compose.html', error_msg='不能发给自己', recent_name=recent_name)
            else:
                id = session['admin_id']
                e = EmailModel(content=content,
                               create_time=datetime.now(),
                               is_trash=0,
                               is_important=0,
                               sender_id=id,
                               receiver_id=receiver_id,
                               is_read=0,
                               title=title,
                               is_draft=0)

                if 'send' in request.form:
                    print('send')
                    db.session.add(e)
                    db.session.commit()
                    return redirect(url_for('mail.sent'))
                else:
                    print('to_draft')
                    e.is_draft = 1
                    db.session.add(e)
                    db.session.commit()
                    return redirect(url_for('mail.draft'))


@bp.route('/trash', methods=['GET', 'POST'])
@login_required
def trash():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    my_emails = [email for email in emails
                 if (session['admin_id'] == email.receiver_id
                     or session['admin_id'] == email.sender_id)
                 and email.is_trash == 1]
    return render_template('d_mail_trash.html', emails=my_emails)


@bp.route('/draft', methods=['GET', 'POST'])
@login_required
def draft():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    my_emails = [email for email in emails
                 if (session['admin_id'] == email.receiver_id
                     or session['admin_id'] == email.sender_id)
                 and email.is_draft == 1 and email.is_trash == 0]
    return render_template('d_mail_draft.html', emails=my_emails)


@bp.route('/compose_draft/<mail_id>', methods=['GET', 'POST'])
@login_required
def compose_draft(mail_id):
    draft_mail = EmailModel.query.filter_by(id=mail_id).first()
    receiver = AdminModel.query.filter_by(id=draft_mail.receiver_id).first().name
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()

    my_emails = [email for email in emails if session['admin_id'] == email.receiver_id]
    recent_id = []
    recent_name = []
    for me in my_emails:
        recent_id.append(me.sender_id)
    admins = AdminModel.query.order_by(AdminModel.id).all()
    for a in admins:
        if a.id in recent_id:
            recent_name.append(a.name)
    return render_template('d_mail_compose.html', draft_mail=draft_mail, receiver=receiver, recent_name=recent_name)


@bp.route('/to_draft', methods=['GET', 'POST'])
@login_required
def to_draft():
    return render_template('d_mail_draft.html')


@bp.route('/sent', methods=['GET', 'POST'])
@login_required
def sent():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    my_emails = [email for email in emails if session['admin_id'] == email.sender_id
                 and email.is_trash is False and email.is_draft is False]
    return render_template('d_mail_sent.html', emails=my_emails)


@bp.route('/filter_read', methods=['GET', 'POST'])
@login_required
def filter_read():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    my_emails = [email for email in emails if
                 1 == email.is_read and email.is_trash is False and email.is_draft is False]
    return render_template('d_mail.html', emails=my_emails)


@bp.route('/filter_unread', methods=['GET', 'POST'])
@login_required
def filter_unread():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    my_emails = [email for email in emails if
                 0 == email.is_read and email.is_trash is False and email.is_draft is False]
    return render_template('d_mail.html', emails=my_emails)


@bp.route('/filter_important', methods=['GET', 'POST'])
@login_required
def filter_important():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    my_emails = [email for email in emails if
                 1 == email.is_important and email.is_trash is False and email.is_draft is False]
    return render_template('d_mail.html', emails=my_emails)


@bp.route('/filter_regular', methods=['GET', 'POST'])
@login_required
def filter_regular():
    emails = EmailModel.query.order_by(EmailModel.create_time.desc()).all()
    my_emails = [email for email in emails if
                 0 == email.is_important and email.is_trash is False and email.is_draft is False]
    return render_template('d_mail.html', emails=my_emails)


@bp.route('transfer', methods=['GET', 'POST'])
@login_required
def transfer():
    pass

blueprints/others.py
import json
import time

import requests
from flask import *
from flask_ckeditor import *

from decorators import *
from .forms import *
from werkzeug.security import *

bp = Blueprint('others', __name__, url_prefix='/others')


@bp.route('/profile')
@login_required
def profile():
    admin = AdminModel.query.filter_by(name=g.name).first()
    return render_template("d_profile.html", admin=admin)


@bp.route('/lockscreen', methods=['POST', 'GET'])
@login_required
def lockscreen():
    if request.method == 'GET':
        return render_template("d_lockscreen.html")
    else:
        form = PasswordForm(request.form)
        password = form.password.data
        admin = AdminModel.query.filter_by(name=g.name).first()
        if check_password_hash(admin.password, password):
            return redirect(url_for('qa.index'))
        else:
            return render_template("d_lockscreen.html", error_msg='密码错误')


@bp.route('/announce', methods=['GET', 'POST'])
@login_required
def announce():
    form = AnnounceForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        A = AnnouncementModel(title=title, content=content)
        db.session.add(A)
        db.session.commit()
        return redirect(url_for('others.announcement'))
    return render_template('f_announce.html', form=form)


@bp.route('/announcement')
#  @login_required
def announcement():
    announcements = AnnouncementModel.query.order_by(AnnouncementModel.create_time.desc()).all()
    return render_template('f_announcement.html', announcement=announcements)


@bp.route('/announcement_bs')
@login_required
def announcement_bs():
    announcements = AnnouncementModel.query.order_by(AnnouncementModel.create_time.desc()).all()
    return render_template('f_announcement_bs.html', announcement=announcements)


@bp.route('/announcement_delete/<a_id>')
@login_required
def announcement_delete(a_id):
    a = AnnouncementModel.query.filter_by(id=a_id).first()
    db.session.delete(a)
    db.session.commit()
    return redirect(url_for('others.announcement_bs'))


@bp.route('/announcement_search/', methods=['POST', 'GET'])
@login_required
def announcement_search():
    ctt = request.form.get('ctt')
    print(ctt)
    if ctt is None:
        ctt = ''
    a = AnnouncementModel.query.order_by(AnnouncementModel.id).all()
    a_list = []
    for r in a:
        if ctt in str(r.id) or ctt in r.content or ctt in str(r.create_time) or ctt in r.title:
            a_list.append(r)
    return render_template('f_announcement_bs.html', announcement=a_list)


@bp.route('/announcement_view/<announcement_id>')
@login_required
def announcement_view(announcement_id):
    a = AnnouncementModel.query.filter_by(id=announcement_id).first()
    return render_template('f_announcement_view.html', a=a)


@bp.route('/calendar')
@login_required
def calendar():
    return render_template('e_calendar.html')


@bp.route('/info_today')
@login_required
def info_today():
    return render_template('f_info_today.html')


@bp.route('/info_history')
@login_required
def info_history():
    return render_template('f_info_history.html')


@bp.route('/mapmarks2json')
def mapmarks2json():
    mms = MapMarkModel.query.order_by(MapMarkModel.id).all()
    jmms = [
        {
            'id': mm.id,
            'long': mm.long,
            'lat': mm.lat,
            'content': mm.content
        }
        for mm in mms
    ]
    print(jmms)
    return json.dumps(jmms, ensure_ascii=False)


@bp.route('/leaflet_map', methods=['POST', 'GET'])
@login_required
def leaflet_map():
    return render_template('f_leaflet.html')


@bp.route('/map_add_mark', methods=['POST', 'GET'])
@login_required
def map_add_mark():
    if request.method == 'GET':
        return redirect(url_for('others.leaflet_map'))
    else:
        long = request.form.get('longitude')
        lat = request.form.get('latitude')
        content = request.form.get('content')
        mm = MapMarkModel.query.filter_by(long=long, lat=lat).first()
        if mm is None:
            mm = MapMarkModel(long=long, lat=lat, content=content)
            db.session.add(mm)
            db.session.commit()
        return redirect(url_for('others.leaflet_map'))


@bp.route('/map_delete_mark', methods=['POST', 'GET'])
@login_required
def map_delete_mark():
    if request.method == 'GET':
        return redirect(url_for('others.leaflet_map'))
    else:
        long = request.form.get('longitudedelete')
        lat = request.form.get('latitudedelete')
        mm = MapMarkModel.query.filter_by(long=long, lat=lat).first()
        print(mm)
        db.session.delete(mm)
        db.session.commit()
        return redirect(url_for('others.leaflet_map'))

blueprints/qa.py
from flask import *
from sqlalchemy.orm import relationship
from model import *
from decorators import *

bp = Blueprint('qa', __name__, url_prefix='/qa')


@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    #  最近五条出入记录
    latest_ann = AnnouncementModel.query.order_by(AnnouncementModel.create_time.desc()).first()
    five_parecord = PARecordModel.query.filter(PARecordModel.person_type != '访客').order_by(PARecordModel.time.desc()).limit(5).all()
    five_parecord_visitor = PARecordModel.query.filter_by(person_type='访客').order_by(PARecordModel.time.desc()).limit(5).all()
    five_resident = []
    five_visitor = []

    for fp, fpv in zip(five_parecord, five_parecord_visitor):
        aim_resident = ResidentModel.query.filter_by(name=fp.name, id=fp.person_id).first()
        aim_visitor = VisitorModel.query.filter_by(name=fpv.name, id=fpv.person_id).first()
        print(five_resident, five_visitor)
        if aim_resident is not None:
            five_resident.append(aim_resident.phone_num[-4:])
        else:
            five_resident.append('unknown')

        if aim_visitor is not None:
            five_visitor.append(aim_visitor.phone_num[-4:])
        else:
            five_visitor.append('unknown')
    return render_template('b_index.html', fr=five_parecord, fp=five_resident,
                           fv=five_visitor, la=latest_ann, fpv=five_parecord_visitor)

templates/Test.html
{% extends "base.html" %}

{% block title %}测试页面{% endblock %}

{% block head %}
{% endblock %}

{% block body %}

{% endblock %}

templates/b_confirm.html
<!DOCTYPE html>
<html lang="Zh-CN">
<head>
  <meta charset="utf-8">
  <title>找回密码</title>
  <!-- Link CSS -->
  <link rel="stylesheet" href="../static/css/style1.css">
</head>
<body>
	<div class="main">
		<div class="top">
            <div class="header"> <h1 class="logo"><a href="#"><img src="../static/img/sus.png" alt=""></a></h1></div>
			<h2>新的密码</h2>
			<h3>下次小心</h3>
		</div>
		<div class="recruit">
			<h4>键入</h4>
			<form method="POST">
                    <div class="field1">
                        <input type="password" name="password" required>
                        <span class="label">密码</span>
                    </div>
                    <div class="field1">
                        <input type="password" name="confirm" required>
                        <span class="label">确认密码</span>
                    </div>
                    <div class="field1">
                        <button type="submit"><a class="sign">确认</a></button>
                    </div>
                    <div>
                        <p class="error-msg" style="">{{ error_msg }}</p>
                    </div>
                </form>
		</div>
	</div>

</body>
</html>

templates/b_login.html
<!DOCTYPE html>
<html lang="Zh-CN">
<head>
  <meta charset="utf-8">
  <title>系统登录</title>
  <!-- Link CSS -->
  <link rel="stylesheet" href="../static/css/style1.css">
</head>
<body>
	<div class="main">
		<div class="top">
            <div class="header"> <h1 class="logo"><a href="#"><img src="../static/img/sus.png" alt=""></a></h1></div>
			<h2>系统登录</h2>
			<h3>谁控制了该系统，谁就控制了小区</h3>
		</div>
		<div class="recruit">
			<h4>登录或是<a href="{{ url_for('auth.forget') }}">忘记密码？</a></h4>

			<form method="POST">
                    <div class="field1">
					<input type="text" name="name" required>
					<span class="label">用户名</span>
                    </div>
                    <div class="field1">
                        <input type="password" name="password" required>
                        <span class="label">密码</span>
                    </div>
                    <div class="field1">
                        <button type="submit"><a class="sign">登录</a></button>
                    </div>
                    <div>
                        <p class="error-msg" style="">{{ error_msg }}</p>
                    </div>
                </form>
		</div>
	</div>

</body>
</html>

templates/c_detect_face_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="ThemeBucket">
  <link rel="shortcut icon" href="#" type="image/png">

  <title>出入平安</title>

  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/otherStyle.css') }}" rel="stylesheet">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="../static/js/html5shiv.js"></script>
    <script src="../static/js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="error-page">

<section>
    <div class="container ">
        <section class="error-wrapper text-center">
            <h1><img alt="" src="{{ url_for('static', filename='img/INGSOC_logo.png') }}"></h1>
            <h2>出入平安</h2>
            <h3>{{ person.name }}</h3>
            <a class="back-btn" href="{{ url_for('qa.index') }}"> 我爱老大哥</a>

        </section>

    </div>
</section>

<!-- Placed js at the end of the document so the pages load faster -->
<script src="{{ url_for('static', filename='js/jquery-1.10.2.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-ui-1.9.2.custom.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-migrate-1.2.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/modernizr.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.nicescroll.js') }}"></script>
<script src="{{ url_for('static', filename='myJS/script.js') }}"></script>


<!--common scripts for all pages-->
<!--<script src="js/scripts.js"></script>-->

</body>
</html>

templates/c_detect_vp.html
{% extends "base.html" %}

{% block title %}扫车牌{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
<div class="wrapper">
    <h3>扫车牌</h3>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <header class="panel-heading">
                你在看着他们，老大哥在看着你
                <span class="tools pull-right">
                    <a href="javascript:" class="fa fa-chevron-down"></a>
                    <a href="javascript:" class="fa fa-times"></a>
                </span>
            </header>
                    <div class="panel-body">
                         <a href="{{ url_for('monitor.detect_vp_in') }}">进入扫车牌</a>
                         <a href="{{ url_for('monitor.detect_vp_out') }}">外出扫车牌</a>
                        <br>
                        <img src="../static/photos/vp/1%20(5).png" alt="">
                    </div>
                <br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/d_mail_sent.html
{% extends "base.html" %}

{% block title %}邮箱{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <div class="wrapper">
            <div class="mail-box">
                <aside class="mail-nav mail-nav-bg-color">
                    <header class="header"> <h4>邮箱</h4> </header>
                    <div class="mail-nav-body">
                        <div class="text-center">
                            <a class="btn btn-compose" href="{{ url_for('mail.compose') }}">
                                写邮件
                            </a>
                        </div>
                        <ul class="nav nav-pills nav-stacked mail-navigation">
                            <li><a href="{{ url_for('mail.mail_main') }}"> <i class="fa fa-inbox"></i> 收件箱</a></li>
                            <li class="active"><a href="{{ url_for('mail.sent') }}"> <i class="fa fa-envelope-o"></i> 已发送邮件<span class="label label-danger pull-right inbox-notification">{{ emails|length }}</span></a></li>
                            <li><a href="{{ url_for('mail.draft') }}"> <i class="fa fa-file-text-o"></i> 草稿</a></li>
                            <li><a href="{{ url_for('mail.trash') }}"> <i class="fa fa-trash-o"></i> 垃圾箱</a></li>
                        </ul>
                    </div>
                </aside>

                <section class="mail-box-info">
                    <header class="header">
                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <a href="{{ url_for('mail.mail_main') }}">
                                    <button class="btn btn-sm btn-primary"><i class="fa fa-refresh"></i></button>
                                </a>
                            </div>
                            <div class="btn-group select">
                                <button data-toggle="dropdown" class="btn btn-primary btn-sm dropdown-toggle">
                                    <span style="width: 70px;" class="dropdown-label">筛选</span>
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu text-left text-sm">
                                    <li><a href="{{ url_for('mail.filter_read') }}">已读邮件</a></li>
                                    <li><a href="{{ url_for('mail.filter_unread') }}">未读邮件</a></li>
                                    <li><a href="{{ url_for('mail.filter_important') }}">重要邮件</a></li>
                                    <li><a href="{{ url_for('mail.filter_regular') }}">普通邮件</a></li>
                                </ul>
                            </div>

                        </div>

                    </header>

                    <section class="mail-list">
                        <ul class="list-group ">
                            {% for email in emails%}
                            <li class="list-group-item">
                                <span class="pull-left chk">
                                    <input type="checkbox"/>
                                </span>
                                <a class="thumb pull-left" href="#"> <img src="../static/img/baoan.png"> </a>
                                <a class="" href="{{ url_for('mail.mail_view', mail_id=email.id) }}"> <small class="pull-right text-muted">{{ email.create_time }}</small>来自 <strong>{{ email.sender.name }}</strong>  <span>主题: <strong>{{ email.title }}</strong> </span> </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </section>

                </section>
            </div>

        </div>
{% endblock %}

templates/d_mail_trash.html
{% extends "base.html" %}

{% block title %}邮箱{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <div class="wrapper">
            <div class="mail-box">
                <aside class="mail-nav mail-nav-bg-color">
                    <header class="header"> <h4>邮箱</h4> </header>
                    <div class="mail-nav-body">
                        <div class="text-center">
                            <a class="btn btn-compose" href="{{ url_for('mail.compose') }}">
                                写邮件
                            </a>
                        </div>
                        <ul class="nav nav-pills nav-stacked mail-navigation">
                            <li><a href="{{ url_for('mail.mail_main') }}"> <i class="fa fa-inbox"></i> 收件箱</a></li>
                            <li><a href="{{ url_for('mail.sent') }}"> <i class="fa fa-envelope-o"></i> 已发送邮件</a></li>
                            <li><a href="{{ url_for('mail.draft') }}"> <i class="fa fa-file-text-o"></i> 草稿 </a></li>
                            <li class="active"><a href="{{ url_for('mail.trash') }}"> <i class="fa fa-trash-o"></i> 垃圾箱<span class="label label-danger pull-right inbox-notification">{{ emails|length }}</span></a></li>
                        </ul>
                    </div>
                </aside>

                <section class="mail-box-info">
                    <header class="header">
                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <a href="{{ url_for('mail.mail_main') }}">
                                    <button class="btn btn-sm btn-primary"><i class="fa fa-refresh"></i></button>
                                </a>
                            </div>
                            <div class="btn-group select">
                                <button data-toggle="dropdown" class="btn btn-primary btn-sm dropdown-toggle">
                                    <span style="width: 70px;" class="dropdown-label">筛选</span>
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu text-left text-sm">
                                    <li><a href="{{ url_for('mail.filter_read') }}">已读邮件</a></li>
                                    <li><a href="{{ url_for('mail.filter_unread') }}">未读邮件</a></li>
                                    <li><a href="{{ url_for('mail.filter_important') }}">重要邮件</a></li>
                                    <li><a href="{{ url_for('mail.filter_regular') }}">普通邮件</a></li>
                                </ul>
                            </div>

                        </div>

                    </header>

                    <section class="mail-list">
                        <ul class="list-group ">
                            {% for email in emails%}
                            <li class="list-group-item">
                                <span class="pull-left chk">
                                    <input type="checkbox"/>
                                </span>
                                <a class="thumb pull-left" href="#"> <img src="../static/img/baoan.png"> </a>
                                <a class="" href="{{ url_for('mail.mail_view', mail_id=email.id) }}"> <small class="pull-right text-muted">{{ email.create_time }}</small>来自 <strong>{{ email.sender.name }}</strong>  <span>主题: <strong>{{ email.title }}</strong> </span> </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </section>

                </section>
            </div>

        </div>
{% endblock %}

templates/f_leaflet.html
{% extends "base.html" %}

{% block title %}LeafLet地图{% endblock %}

{% block head %}
    <link href="https://cdn.bootcdn.net/ajax/libs/leaflet/1.9.3/leaflet.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/leaflet/1.9.3/leaflet.js"></script>
{% endblock %}

{% block body %}
	<div class="wrapper">
    <h3>标记点</h3>
    <div class="panel-body">
        <form id="mapmark" method="post" action="{{ url_for('others.map_add_mark') }}">
          <label for="latitude">经度:</label>
          <input type="text" id="latitude" name="latitude" required>

          <label for="longitude">纬度:</label>
          <input type="text" id="longitude" name="longitude" required>

          <label for="content">内容:</label>
          <input type="text" id="content" name="content" required>
          <button type="submit" class="btn-primary btn-sm">提交</button>
        </form>

        <form id="mapmarkdelete" method="post" action="{{ url_for('others.map_delete_mark') }}">
          <label for="latitudedelete"></label>
          <input type="text" id="latitudedelete" name="latitudedelete" required hidden>

          <label for="longitudedelete"></label>
          <input type="text" id="longitudedelete" name="longitudedelete" required hidden>

          <label for="contentdelete">内容:</label>
          <input type="text" id="contentdelete" name="contentdelete" required>

          <button type="submit" class="btn-danger btn-sm">删除</button>
        </form>
        <div id="mapid" style="height: 500px;"></div>
    </div>
</div>
<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
 $.ajax({
  url: 'http://127.0.0.1:5000/others/mapmarks2json',
  method: 'GET',
  success: function(jmms) {
    console.log(jmms);
    var latitudeInput = document.getElementById('latitude');
    var longitudeInput = document.getElementById('longitude');
    var latitudeInputDelete = document.getElementById('latitudedelete');
    var longitudeInputDelete = document.getElementById('longitudedelete');
    var contentInputDelete = document.getElementById('contentdelete')

    var mymap = L.map('mapid').setView([34.811729, 113.504621], 16);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
      maxZoom: 18,
    }).addTo(mymap);

    var jsonData = JSON.parse(jmms); // 将 JSON 字符串解析为对象

    for (var i = 0; i < jsonData.length; i++) {
      var item = jsonData[i];
      var marker = L.marker([item.lat, item.long]).addTo(mymap).bindPopup(item.content).openPopup();

      marker.content = item.content;  // 将content作为自定义属性附加到标记上

      marker.on('click', function(e) {
        var markerLatLng = e.latlng;
        latitudeInputDelete.value = markerLatLng.lat.toFixed(6);
        longitudeInputDelete.value = markerLatLng.lng.toFixed(6);
        contentInputDelete.value = e.target.content;
        console.log('点击的坐标：', markerLatLng.lat.toFixed(6), markerLatLng.lng.toFixed(6));
        console.log('点击的content：', e.target.content);  // 打印出content属性的值
      });
    }


    function onMapClick(e) {
      var latlng = e.latlng;
      var latitude = latlng.lat.toFixed(6);
      var longitude = latlng.lng.toFixed(6);

      // 将经纬度填充到表单输入框中
      latitudeInput.value = latitude;
      longitudeInput.value = longitude;

      console.log('点击的坐标：', latitude, longitude);
    }

    mymap.on('click', onMapClick);
  },
  error: function(error) {
    console.log('未拿到');
    console.error(error);
  }
});

</script>


{% endblock %}